blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache, cache_page

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='articles'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<str:slug>/', ArticleUpdateView.as_view(), name='update'),
    path('delete/<str:slug>/', ArticleDeleteView.as_view(), name='delete'),
    path('articles/<str:slug>/', cache_page(60)(ArticleDetailView.as_view()), name='view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('articles/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import HomeTemplateView, ClientCreateView, MessageCreateView, MailingCreateView, ClientListView, \
    MessageListView, MailingListView, ClientUpdateView, ClientDeleteView, MessageUpdateView, MessageDeleteView, \
    MailingUpdateView, MailingDeleteView, status_mailing, LogListView, LogDetailView, LogDeleteView

app_name = MailingConfig.name


urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home_page'),

    path('add', ClientCreateView.as_view(), name='add_client'),
    path('client_list', ClientListView.as_view(), name='client_list'),
    path('edit_client/<int:pk>', ClientUpdateView.as_view(), name='edit_client'),
    path('delete_client/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),

    path('create_message', MessageCreateView.as_view(), name='create_message'),
    path('message_list', MessageListView.as_view(), name='message_list'),
    path('edit_message/<int:pk>', MessageUpdateView.as_view(), name='edit_message'),
    path('delete_message/<int:pk>', MessageDeleteView.as_view(), name='delete_message'),

    path('create_mailing', MailingCreateView.as_view(), name='create_mailing'),
    path('mailing_list', MailingListView.as_view(), name='mailing_list'),
    path('edit_mailing/<int:pk>', MailingUpdateView.as_view(), name='edit_mailing'),
    path('delete_mailing/<int:pk>', MailingDeleteView.as_view(), name='delete_mailing'),
    path('status_mailing/<int:pk>', status_mailing, name='status_mailing'),

    path('log_list', LogListView.as_view(), name='log_list'),
    path('log_detail/<int:pk>', cache_page(60)(LogDetailView.as_view()), name='log_detail'),
    path('delete_log/<int:pk>', LogDeleteView.as_view(), name='delete_log'),
]

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import LoginUserView, LogoutUserView, RegisterUserView, verification, UserUpdateView, \
    generate_password, UserListView, status_user

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('verification/<str:code>/', verification, name='verification'),
    path('profile/genpassword', generate_password, name='genpassword'),
    path('profile/', UserUpdateView.as_view(), name='profile'),

    path('user_list/', UserListView.as_view(), name='user_list'),
    path('status_user/<int:pk>', status_user, name='status_user'),


]

blog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    """Модель таблицы - статьи"""
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, **NULLABLE, verbose_name='slug')
    image = models.ImageField(upload_to='products/', **NULLABLE, verbose_name='Превью')
    content = models.TextField(max_length=1000, verbose_name='Содержимое')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')
    date_added = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    views_count = models.IntegerField(verbose_name='Количество просмотров', default=0)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, default=1,
                             verbose_name='Пользователь', **NULLABLE)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        """Класс отображения метаданных"""
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

mailing/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}

PERIODISITY_CHOISES = (
    ('day', 'Раз в день'),
    ('week', 'Раз в неделю'),
    ('month', 'Раз в месяц'),
)

STATUS_CHOISES = (
    ('created', 'Создана'),
    ('started', 'Запущена'),
    ('completed', 'Завершена'),
)


class Mailing(models.Model):
    """Модель таблицы - товары"""
    time = models.TimeField(verbose_name='Время рассылки')
    date = models.DateField(verbose_name='Дата рассылки')
    periodisity = models.CharField(max_length=20, choices=PERIODISITY_CHOISES, default='month',
                                   verbose_name='Периодичность')
    status = models.CharField(max_length=10, choices=STATUS_CHOISES, default='created', verbose_name='Статус рассылки')
    client = models.ManyToManyField('Client', verbose_name='Клиент')
    message = models.ForeignKey('Message', on_delete=models.CASCADE, verbose_name='Сообщение')

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1, verbose_name='Пользователь')

    def __str__(self):
        return f'Дата - {self.date}: \n' \
               f'Сообщение - {self.message}'

    class Meta:
        """Класс отображения метаданных"""
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

        permissions = [
            (
                'set_status',
                'Can change status'
            )
        ]


class Client(models.Model):
    """Модель таблицы - товары"""
    email = models.EmailField(max_length=150, verbose_name='Контактная почта')
    full_name = models.CharField(max_length=150, verbose_name='ФИО')
    comment = models.TextField(max_length=500, **NULLABLE, verbose_name='Коментарий')

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1, verbose_name='Пользователь')

    def __str__(self):
        return f'{self.email}'

    class Meta:
        """Класс отображения метаданных"""
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    """Модель таблицы - товары"""
    subject = models.CharField(max_length=150, verbose_name='Тема письма')
    body = models.TextField(max_length=1000, **NULLABLE, verbose_name='Тело письма')

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1, verbose_name='Пользователь')

    def __str__(self):
        return f'{self.subject}'

    class Meta:
        """Класс отображения метаданных"""
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'


class Log(models.Model):
    """Модель таблицы - товары"""
    time = models.DateTimeField(auto_now_add=True, verbose_name='Время последеней попытки')
    status = models.BooleanField(verbose_name='Статус попытки')
    server_response = models.CharField(max_length=150, verbose_name='Ответ сервера', **NULLABLE)
    mailing = models.ForeignKey('Mailing', on_delete=models.CASCADE, verbose_name='Рассылка', **NULLABLE)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1, verbose_name='Пользователь')

    def __str__(self):
        return f'{self.time}'

    class Meta:
        """Класс отображения метаданных"""
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import random

random_code = ''.join(random.sample('0123456789', 5))
NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    """Модель таблицы User"""
    username = None

    email = models.EmailField(unique=True, verbose_name='Почта')
    phone = models.CharField(max_length=35, verbose_name='Телефон', **NULLABLE)
    country = models.CharField(max_length=25, verbose_name='Страна', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    verify_code = models.CharField(max_length=5, default=random_code, verbose_name='Код верификации')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        """Класс отображения метаданных"""
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

        permissions = [
            (
                'set_is_active',
                'Can deactivate user'
            )
        ]

mailing/forms.py
from django import forms

from mailing.models import Client, Message, Mailing


class StyleFormMixin:
    """Миксин для стилизации форм"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    """Форма для модели Client"""

    class Meta:
        model = Client
        exclude = ('user',)


class MessageForm(StyleFormMixin, forms.ModelForm):
    """Форма для модели Message"""

    class Meta:
        model = Message
        exclude = ('user',)


class MailingForm(StyleFormMixin, forms.ModelForm):
    """Форма для модели Mailing"""

    class Meta:
        model = Mailing
        exclude = ('status', 'user')
        widgets = {
            'time':  forms.TimeInput(
                attrs={'type': 'time', }
            ),
            'date': forms.DateInput(
                attrs={'type': 'date', }
            )
        }

mailing/views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
import random
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, TemplateView, CreateView, UpdateView, DeleteView, DetailView

from blog.models import Blog
from mailing.forms import ClientForm, MessageForm, MailingForm
from mailing.models import Client, Message, Mailing, Log


class HomeTemplateView(TemplateView):
    """Контроллер главной страницы"""
    template_name = 'mailing/index.html'

    def get_context_data(self, *args, **kwargs):
        """Вывод информации на главную страницу"""
        context_data = super().get_context_data(*args, **kwargs)
        clients_count = len(Client.objects.filter(user=self.request.user.pk))
        mailing_count = len(Mailing.objects.filter(user=self.request.user.pk))
        active_mailing = len(Mailing.objects.filter(user=self.request.user.pk, status='created'))
        blog_list = [blog for blog in Blog.objects.all()]
        random_blog_list = random.sample(blog_list, 3)
        context_data['clients_count'] = clients_count
        context_data['mailing_count'] = mailing_count
        context_data['active_mailing'] = active_mailing
        context_data['random_blog_list'] = random_blog_list
        return context_data


class ClientCreateView(LoginRequiredMixin, CreateView):
    """Контроллер страницы добавления нового клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:home_page')

    def form_valid(self, form):
        """Добавление пользователя к клиенту"""
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class ClientListView(LoginRequiredMixin, ListView):
    """Контроллер страницы клиентов"""
    model = Client

    def get_queryset(self):
        """Вывод клиентов пользователя"""
        return super().get_queryset().filter(user=self.request.user)


class ClientUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Контроллер страницы редактирования клиентов"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def test_func(self):
        user = self.request.user
        if user == self.get_object().user:
            return True
        return self.handle_no_permission()


class ClientDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Контроллер удаления клиента"""
    model = Client
    success_url = reverse_lazy('mailing:client_list')

    def test_func(self):
        user = self.request.user
        if user == self.get_object().user:
            return True
        return self.handle_no_permission()


class MessageCreateView(LoginRequiredMixin, CreateView):
    """Контроллер страницы добавления нового сообщения"""
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_list')

    def form_valid(self, form):
        """Добавление пользователя к сообщению"""
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Контроллер страницы редактирования сообщения"""
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_list')

    def test_func(self):
        user = self.request.user
        if user == self.get_object().user:
            return True
        return self.handle_no_permission()


class MessageDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Контроллер страницы удаления сообщения"""
    model = Message
    success_url = reverse_lazy('mailing:home_page')

    def test_func(self):
        user = self.request.user
        if user == self.get_object().user:
            return True
        return self.handle_no_permission()


class MessageListView(LoginRequiredMixin, ListView):
    """Контроллер страницы сообщений"""
    model = Message

    def get_queryset(self):
        """Вывод сообщений пользователя"""
        return super().get_queryset().filter(user=self.request.user)


class MailingCreateView(LoginRequiredMixin, CreateView):
    """Контроллер страницы добавления новой рассылки"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:home_page')

    def form_valid(self, form):
        """Добавление пользователя к рассылке"""
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Контроллер страницы редактирования рассылки"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def test_func(self):
        user = self.request.user
        if user == self.get_object().user:
            return True
        return self.handle_no_permission()


class MailingDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Контроллер страницы удаления рассылки"""
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')

    def test_func(self):
        user = self.request.user
        if user == self.get_object().user:
            return True
        return self.handle_no_permission()


class MailingListView(LoginRequiredMixin, ListView):
    """Контроллер страницы рассылок"""
    model = Mailing

    def get_queryset(self):
        """Вывод рассылок пользователя либо всех рассылок для модератора"""
        if self.request.user.has_perm('mailing.view_mailing'):
            return super().get_queryset()
        return super().get_queryset().filter(user=self.request.user)


def status_mailing(request, pk):
    """Контроллер смены статуса рассылки"""
    mailing = Mailing.objects.get(pk=pk)
    if request.user == mailing.user or request.user.has_perm('mailing.set_status'):
        if mailing.status == 'created':
            mailing.status = 'completed'
            mailing.save()
        elif mailing.status == 'completed':
            mailing.status = 'created'
            mailing.save()
    return redirect(reverse('mailing:mailing_list'))


class LogListView(LoginRequiredMixin, ListView):
    """Контроллер страницы логов"""
    model = Log

    def get_queryset(self):
        """Вывод сообщений пользователя"""
        return super().get_queryset().filter(user=self.request.user)


class LogDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    """Контроллер страницы лога"""
    model = Log

    def test_func(self):
        user = self.request.user
        if user == self.get_object().user:
            return True
        return self.handle_no_permission()


class LogDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Контроллер удаления лога"""
    model = Log
    success_url = reverse_lazy('mailing:log_list')

    def test_func(self):
        user = self.request.user
        if user == self.get_object().user:
            return True
        return self.handle_no_permission()

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">

<head>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.115.4">
    <title>MyMailing</title>


    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            width: 100%;
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
            --bd-violet-bg: #712cf9;
            --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

            --bs-btn-font-weight: 600;
            --bs-btn-color: var(--bs-white);
            --bs-btn-bg: var(--bd-violet-bg);
            --bs-btn-border-color: var(--bd-violet-bg);
            --bs-btn-hover-color: var(--bs-white);
            --bs-btn-hover-bg: #6528e0;
            --bs-btn-hover-border-color: #6528e0;
            --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
            --bs-btn-active-color: var(--bs-btn-hover-color);
            --bs-btn-active-bg: #5a23c8;
            --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
            z-index: 1500;
        }

    </style>


</head>

<body>
<header data-bs-theme="dark">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            {% if perms.users.view_user %}
            <a class="navbar-brand" href="{% url 'users:user_list' %}">Пользователи</a>
            {% endif %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'mailing:home_page' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mailing:client_list' %}">Клиенты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mailing:message_list' %}">Сообщения</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mailing:mailing_list' %}">Рассылки</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mailing:log_list' %}">История рассылок</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'blog:articles' %}">Статьи<span class="sr-only">(current)</span></a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'users:profile' %}">Профиль <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'users:logout' %}">Выйти <span class="sr-only">(current)</span></a>
                    </li>
                     {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'users:login' %}">Войти <span class="sr-only">(current)</span></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
{% block content %}
{% endblock %}

<script src="{% static 'js/bootstrap.bundle.min.js' %}"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>

</html>

mailing/templates/mailing/client_confirm_delete.html
{%extends 'mailing/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <br />
  <h4>Удалить клиента</h4>
</div>
<main>
    <div class="card">
        <div class="card-body">
            <div class="col-md-7 col-lg-8">
              <form enctype="multipart/form-data" class="needs-validation" method="post">
                {% csrf_token %}
                <p>Хотите удалить клиента {{client.email}}?</p>
                <button type="submit" class="btn btn-danger">Подтвердить</button>
                <a href="{% url 'mailing:client_list' %}" class="btn btn-warning">Отмена</a>
              </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/client_list.html
{%extends 'mailing/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <br/>
    <h4>Список ваших клиентов</h4>
</div>
<div class="table-responsive small">

    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">E-mail</th>
            <th scope="col">ФИО</th>
            <th scope="col">Коментарий</th>
            <th scope="col">Прочее</th>
        </tr>
        </thead>
        <tbody>
        {% for client in client_list %}
        <tr>
            <td>{{client.pk}}</td>
            <td>{{client.email}}</td>
            <td>{{client.full_name}}</td>
            <td>{{client.comment}}</td>
            <td>
                <div class="btn-group">
                    <a type="button" class="btn btn-outline-primary btn-sm"
                       href="{% url 'mailing:edit_client' client.id %}">Редактировать</a>
                    <a type="button" class="btn btn-outline-danger btn-sm"
                       href="{% url 'mailing:delete_client' client.id %}">Удалить</a>
                </div>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <a type="button" class="btn btn-outline-primary btn-sm" href="{% url 'mailing:add_client' %}">Добавить клиента</a>
</div>
{% endblock %}

mailing/templates/mailing/index.html
{%extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container py-3">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">MyMailing</h1>
        <p class="lead">Добро пожаловать в MyMailing - лучший сервис e-mail рассылок. Создавайте свою базу клиентов,
            оформляйте письма и ведите статистику доставки. Чтобы создать рассылку для начала добавьте клиента, затем
            создайте сообщение. После создайте рассылки для своих клиентов</p>
    </div>
    <main>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h2 class="my-0 fw-normal">Клиенты</h2>
                    </div>
                    <div class="card-body">
                        <h4>Количество ваших уникальных клиентов - {{clients_count}}</h4>
                    </div>
                    <div class="card-footer">
                        <a type="button" class="btn btn-outline-primary"
                           href="{% url 'mailing:add_client' %}">Добавить</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h2 class="my-0 fw-normal">Сообщения</h2>
                    </div>
                    <div class="card-body">
                        <h4>Создайте сообщение для рассылки</h4>
                    </div>
                    <div class="card-footer">
                        <a type="button" class="btn btn-outline-primary" href="{% url 'mailing:create_message' %}">Создать</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h2 class="my-0 fw-normal">Рассылки</h2>
                    </div>
                    <div class="card-body">
                        <h4>Всего рассылок - {{mailing_count}}</h4>
                        <h4>Активных рассылок - {{active_mailing}}</h4>
                    </div>
                    <div class="card-footer">
                        <a type="button" class="btn btn-outline-primary" href="{% url 'mailing:create_mailing' %}">Создать</a>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Случайные статьи</h1>
    </div>
    {% for blog in random_blog_list %}
    <div class="row mb-2">
        <div class="col-2"></div>
        <div class="col-md-8">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col-auto d-none d-lg-block">
                    <img src="{% mediapath blog.image %}" width="200" height="250" class="bd-placeholder-img"
                         alt="{{blog.title}}">
                </div>
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-primary-emphasis">{{blog.date_added}}</strong>
                    <h3 class="mb-0">{{blog.title}}</h3>
                    <div class="mb-1 text-body-secondary">{{blog.views_count}} просмотров</div>
                    <p class="card-text mb-auto">{{blog.content|slice:100}}...</p>
                    <div class="row">
                        <div class="col-6">
                            <a href="{% url 'blog:view' blog.slug %}"
                               class="icon-link gap-1 icon-link-hover stretched-link">
                                Читать далее
                            </a>
                        </div>
                        <div class="col-6">
                            {% if item.user == user or perms.blog.change_blog %}
                            <div class="btn-group">
                                <a type="button" class="btn btn-outline-primary"
                                   href="{% url 'blog:update' blog.slug %}">Редактировать</a>
                                <a type="button" class="btn btn-outline-danger"
                                   href="{% url 'blog:delete' blog.slug %}">Удалить</a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}