blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache, cache_page

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='articles'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<str:slug>/', ArticleUpdateView.as_view(), name='update'),
    path('delete/<str:slug>/', ArticleDeleteView.as_view(), name='delete'),
    path('articles/<str:slug>/', cache_page(60)(ArticleDetailView.as_view()), name='view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('articles/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    """Модель таблицы - статьи"""
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, **NULLABLE, verbose_name='slug')
    image = models.ImageField(upload_to='products/', **NULLABLE, verbose_name='Превью')
    content = models.TextField(max_length=1000, verbose_name='Содержимое')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')
    date_added = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    views_count = models.IntegerField(verbose_name='Количество просмотров', default=0)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, default=1,
                             verbose_name='Пользователь', **NULLABLE)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        """Класс отображения метаданных"""
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

blog/forms.py
from django import forms
from blog.models import Blog
from mailing.forms import StyleFormMixin


class BlogForm(StyleFormMixin, forms.ModelForm):
    """Форма для модели Blog"""

    class Meta:
        model = Blog
        fields = ('title', 'content', 'image', 'is_published')

blog/views.py
from pytils.translit import slugify

from blog.forms import BlogForm
from blog.models import Blog

from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin


class ArticleListView(LoginRequiredMixin, ListView):
    """Контроллер отображения страницы статей"""
    model = Blog

    def get_queryset(self, *args, **kwargs):
        """Отображение только опубликованных статей"""
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class ArticleDetailView(LoginRequiredMixin, DetailView):
    """Контроллер отображения отдельной статьи"""
    model = Blog

    def get_object(self, queryset=None):
        """Реализация счетчика просмотров"""
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class ArticleCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания статьи"""
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:articles')

    def form_valid(self, form):
        """Генерация slug к статье"""
        if form.is_valid():
            new_article = form.save()
            new_article.user = self.request.user
            new_article.slug = slugify(new_article.title)
            new_article.save()
        return super().form_valid(form)


class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Контроллер редактирования статьи"""
    model = Blog
    form_class = BlogForm

    def test_func(self):
        user = self.request.user
        if user == self.get_object().user or user.has_perm('blog.change_blog'):
            return True
        return self.handle_no_permission()

    def form_valid(self, form):
        """Обновление slug"""
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        """Редирект на статью"""
        return reverse('blog:view', args=[self.kwargs.get('slug')])


class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Контроллер удаления статьи"""
    model = Blog
    success_url = reverse_lazy('blog:articles')

    def test_func(self):
        user = self.request.user
        if user == self.get_object().user or user.has_perm('blog.delete_blog'):
            return True
        return self.handle_no_permission()

blog/templates/blog/blog_confirm_delete.html
{%extends 'mailing/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <br />
    <h4>
        Удалить статью
    </h4>
</div>
<main>
    <div class="card">
        <div class="card-body">
            <div class="col-md-7 col-lg-8">
              <form enctype="multipart/form-data" class="needs-validation" method="post">
                {% csrf_token %}
                <p>Хотите удалить статью {{object.title}}?</p>
                <button type="submit" class="btn btn-danger">Подтвердить</button>
                <a href="{% url 'blog:articles' %}" class="btn btn-warning">Отмена</a>
              </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

blog/templates/blog/blog_detail.html
{%extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <br />
    <h4>{{object.title}}</h4>
</div>
<div class="col-12">
  <div class="row">
    <div class="col-8">
        <img src="{% mediapath object.image %}" width="200" height="250" class="bd-placeholder-img" alt="{{product.title}}">
        <span class="d-flex align-items-center ms-3">
            {{object.date_added}}
        </span>
        <div class="d-flex align-items-center mb-4 text-muted author-info">
            <span>{{object.views_count}} просмотров</span>
        </div>
        <p>{{object.content}}</p>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{%extends 'mailing/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <br />
    <h4>
        {% if object %}
            Редактировать
        {% else %}
            Добавить статью
        {% endif %}
    </h4>
</div>
{% include 'mailing/includes/inc_form.html' %}
{% endblock %}

blog/templates/blog/blog_list.html
{%extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <br/>
    <h4>Статьи</h4>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить статью</a>
</div>
{% for item in object_list %}
<div class="row mb-2">
    <div class="col-md-8">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col-auto d-none d-lg-block">
                <img src="{% mediapath item.image %}" width="200" height="250" class="bd-placeholder-img"
                     alt="{{product.title}}">
            </div>
            <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-primary-emphasis">{{item.date_added}}</strong>
                <h3 class="mb-0">{{item.title}}</h3>
                <div class="mb-1 text-body-secondary">{{item.views_count}} просмотров</div>
                <p class="card-text mb-auto">{{item.content|slice:100}}...</p>
                <div class="row">
                    <div class="col-6">
                        <a href="{% url 'blog:view' item.slug %}"
                           class="icon-link gap-1 icon-link-hover stretched-link">
                            Читать далее
                        </a>
                    </div>
                    <div class="col-6">
                        {% if item.user == user or perms.blog.change_blog %}
                        <div class="btn-group">
                            <a type="button" class="btn btn-outline-primary" href="{% url 'blog:update' item.slug %}">Редактировать</a>
                            <a type="button" class="btn btn-outline-danger" href="{% url 'blog:delete' item.slug %}">Удалить</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}