blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache, cache_page

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='articles'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<str:slug>/', ArticleUpdateView.as_view(), name='update'),
    path('delete/<str:slug>/', ArticleDeleteView.as_view(), name='delete'),
    path('articles/<str:slug>/', cache_page(60)(ArticleDetailView.as_view()), name='view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('articles/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import LoginUserView, LogoutUserView, RegisterUserView, verification, UserUpdateView, \
    generate_password, UserListView, status_user

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('verification/<str:code>/', verification, name='verification'),
    path('profile/genpassword', generate_password, name='genpassword'),
    path('profile/', UserUpdateView.as_view(), name='profile'),

    path('user_list/', UserListView.as_view(), name='user_list'),
    path('status_user/<int:pk>', status_user, name='status_user'),


]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import random

random_code = ''.join(random.sample('0123456789', 5))
NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    """Модель таблицы User"""
    username = None

    email = models.EmailField(unique=True, verbose_name='Почта')
    phone = models.CharField(max_length=35, verbose_name='Телефон', **NULLABLE)
    country = models.CharField(max_length=25, verbose_name='Страна', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    verify_code = models.CharField(max_length=5, default=random_code, verbose_name='Код верификации')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        """Класс отображения метаданных"""
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

        permissions = [
            (
                'set_is_active',
                'Can deactivate user'
            )
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from mailing.forms import StyleFormMixin
from users.models import User


class RegisterForm(StyleFormMixin, UserCreationForm):
    """Форма для регистрации"""
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(StyleFormMixin, UserChangeForm):
    """Форма для профиля пользователя"""
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'avatar', 'country', 'phone')

    def __init__(self, *args, **kwargs):
        """Скрытие поля password"""
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class ListUserForm(StyleFormMixin, forms.ModelForm):
    """Форма модели User для списка"""

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'country')

users/views.py
import random
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.core.mail import send_mail

from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView
from django.shortcuts import redirect
from config.settings import EMAIL_HOST_USER
from mailing.models import Message
from mailing.services import send_mailing
from users.forms import RegisterForm, UserForm, ListUserForm
from users.models import User
from django.contrib.messages.views import SuccessMessageMixin


class LoginUserView(LoginView):
    """Контроллер страницы входа"""
    template_name = 'users/login.html'


class LogoutUserView(LogoutView):
    """Контроллер выхода из аккаунта"""
    pass


class RegisterUserView(SuccessMessageMixin, CreateView):
    """Контроллер страницы регистрации"""
    model = User
    form_class = RegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def get_success_message(self, cleaned_data):
        """Сообщение на страницу входа"""
        return 'Вам на почту отправлено письмо, для прохождения верификации перейдите по ссылку в письме'

    def form_valid(self, form):
        """Верификация по ссылке через почту"""
        new_user = form.save()
        code = ''.join(random.sample('0123456789', 5))
        new_user.verify_code = code
        new_user.is_active = False
        send_mail(
            'Верификация',
            f'Перейдите по ссылке для верификации: http://127.0.0.1:8000/users/verification/{code}',
            EMAIL_HOST_USER,
            [new_user.email]
        )
        return super().form_valid(form)


def verification(request, code):
    """Контроллер подтверждения верификации"""
    user = User.objects.get(verify_code=code)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class UserUpdateView(UpdateView):
    """Контроллер страницы редактирования профиля"""
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        """Отключение необходимости получения pk"""
        return self.request.user


def generate_password(request):
    """Контроллер смены пароля и отправка нового сгенерированного пароля на почту"""
    new_password = User.objects.make_random_password()
    request.user.set_password(new_password)
    request.user.save()
    message = Message.objects.create(subject='Смена пароля', body=f'Ваш новый пароль для авторизации: {new_password}',
                                     user=User.objects.get(pk=request.user.pk))
    send_mailing([request.user.email], message)
    messages.success(request, 'Вам на почту отправлено письмо с новым паролем для вашего аккаунта')
    return redirect(reverse('users:login'))


class UserListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    """Контроллер страницы списка пользователей"""
    model = User
    form_class = ListUserForm
    permission_required = 'users.view_user'


@permission_required('users.set_is_active')
def status_user(request, pk):
    """Контроллер смены статуса пользователя"""
    user = User.objects.get(pk=pk)
    if not user.is_superuser:
        if user.is_active is True:
            user.is_active = False
            user.save()
        elif user.is_active is False:
            user.is_active = True
            user.save()
        return redirect(reverse('users:user_list'))

users/templates/users/login.html
{%extends 'mailing/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    {% if messages %}
        <div class="alert alert-warning">
            {% for message in messages %}
                {{ message }}<br/>
            {% endfor %}
        </div>
    {% endif %}
</div>

<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>
                    <a class="btn btn-success" href="{% url 'users:register' %}">Регистрация</a>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{%extends 'mailing/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <br/>
    <h1 class="display-4">Регистрация</h1>
</div>
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Зарегистрироваться</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{%extends 'mailing/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <br/>
    <h4 class="display-4">Редактировать профиль</h4>
</div>
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <div class="card">
            <div class="card-header">Мой профиль</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:genpassword' %}" class="btn btn-danger">Сгенерировать новый пароль</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{%extends 'mailing/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <br />
  <h4>Список пользователей</h4>
</div>
<div class="table-responsive small">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">email</th>
              <th scope="col">Имя</th>
              <th scope="col">Фамилия</th>
              <th scope="col">Страна</th>
              <th scope="col">Прочее</th>
            </tr>
          </thead>
          <tbody>
          {% for item in user_list %}
            <tr>
              <td>{{item.pk}}</td>
              <td>{{item.email}}</td>
              <td>{{item.first_name}}</td>
              <td>{{item.last_name}}</td>
              <td>{{item.country}}</td>
              <td>
                    {% if item.is_active == False and perms.users.set_is_active  %}
                    <a type="button" class="btn btn-outline-warning btn-sm" href="{% url 'users:status_user' user.pk %}">Разблокировать</a>
                    {% elif item.is_active == True and item.is_superuser == False and perms.users.set_is_active and item != user %}
                    <a type="button" class="btn btn-outline-success btn-sm" href="{% url 'users:status_user' user.pk %}">Заблокировать</a>
                    {% endif %}
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
{% endblock %}